// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: proto/card.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type PageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedPage string `protobuf:"bytes,1,opt,name=requested_page,json=requestedPage,proto3" json:"requested_page,omitempty"`
}

func (x *PageReply) Reset() {
	*x = PageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReply) ProtoMessage() {}

func (x *PageReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReply.ProtoReflect.Descriptor instead.
func (*PageReply) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{1}
}

func (x *PageReply) GetRequestedPage() string {
	if x != nil {
		return x.RequestedPage
	}
	return ""
}

var File_proto_card_proto protoreflect.FileDescriptor

var file_proto_card_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x09, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50, 0x61, 0x67, 0x65, 0x32,
	0x43, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x47, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x11,
	0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_card_proto_rawDescOnce sync.Once
	file_proto_card_proto_rawDescData = file_proto_card_proto_rawDesc
)

func file_proto_card_proto_rawDescGZIP() []byte {
	file_proto_card_proto_rawDescOnce.Do(func() {
		file_proto_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_card_proto_rawDescData)
	})
	return file_proto_card_proto_rawDescData
}

var file_proto_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_card_proto_goTypes = []interface{}{
	(*PageRequest)(nil), // 0: card.PageRequest
	(*PageReply)(nil),   // 1: card.PageReply
}
var file_proto_card_proto_depIdxs = []int32{
	0, // 0: card.ComponentsGetter.GetPage:input_type -> card.PageRequest
	1, // 1: card.ComponentsGetter.GetPage:output_type -> card.PageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_card_proto_init() }
func file_proto_card_proto_init() {
	if File_proto_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_proto_goTypes,
		DependencyIndexes: file_proto_card_proto_depIdxs,
		MessageInfos:      file_proto_card_proto_msgTypes,
	}.Build()
	File_proto_card_proto = out.File
	file_proto_card_proto_rawDesc = nil
	file_proto_card_proto_goTypes = nil
	file_proto_card_proto_depIdxs = nil
}
