/**
 * @fileoverview gRPC-Web generated client stub for card
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: api/proto/card.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.card = require('./card_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.card.ComponentsGetterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.card.ComponentsGetterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.card.PageRequest,
 *   !proto.card.PageReply>}
 */
const methodDescriptor_ComponentsGetter_GetPage = new grpc.web.MethodDescriptor(
  '/card.ComponentsGetter/GetPage',
  grpc.web.MethodType.UNARY,
  proto.card.PageRequest,
  proto.card.PageReply,
  /**
   * @param {!proto.card.PageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.card.PageReply.deserializeBinary
);


/**
 * @param {!proto.card.PageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.card.PageReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.card.PageReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.card.ComponentsGetterClient.prototype.getPage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/card.ComponentsGetter/GetPage',
      request,
      metadata || {},
      methodDescriptor_ComponentsGetter_GetPage,
      callback);
};


/**
 * @param {!proto.card.PageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.card.PageReply>}
 *     Promise that resolves to the response
 */
proto.card.ComponentsGetterPromiseClient.prototype.getPage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/card.ComponentsGetter/GetPage',
      request,
      metadata || {},
      methodDescriptor_ComponentsGetter_GetPage);
};


//module.exports = proto.card;
export default proto.card.ComponentsGetterClient;

