// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: proto/card.proto

package card

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComponentsGetterClient is the client API for ComponentsGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComponentsGetterClient interface {
	GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageReply, error)
}

type componentsGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewComponentsGetterClient(cc grpc.ClientConnInterface) ComponentsGetterClient {
	return &componentsGetterClient{cc}
}

func (c *componentsGetterClient) GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageReply, error) {
	out := new(PageReply)
	err := c.cc.Invoke(ctx, "/card.ComponentsGetter/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComponentsGetterServer is the server API for ComponentsGetter service.
// All implementations must embed UnimplementedComponentsGetterServer
// for forward compatibility
type ComponentsGetterServer interface {
	GetPage(context.Context, *PageRequest) (*PageReply, error)
	mustEmbedUnimplementedComponentsGetterServer()
}

// UnimplementedComponentsGetterServer must be embedded to have forward compatible implementations.
type UnimplementedComponentsGetterServer struct {
}

func (UnimplementedComponentsGetterServer) GetPage(context.Context, *PageRequest) (*PageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedComponentsGetterServer) mustEmbedUnimplementedComponentsGetterServer() {}

// UnsafeComponentsGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComponentsGetterServer will
// result in compilation errors.
type UnsafeComponentsGetterServer interface {
	mustEmbedUnimplementedComponentsGetterServer()
}

func RegisterComponentsGetterServer(s grpc.ServiceRegistrar, srv ComponentsGetterServer) {
	s.RegisterService(&ComponentsGetter_ServiceDesc, srv)
}

func _ComponentsGetter_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentsGetterServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.ComponentsGetter/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentsGetterServer).GetPage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComponentsGetter_ServiceDesc is the grpc.ServiceDesc for ComponentsGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComponentsGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.ComponentsGetter",
	HandlerType: (*ComponentsGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPage",
			Handler:    _ComponentsGetter_GetPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/card.proto",
}
